Fix compilation error due to syntex mismatched types
Error:
build.rs:27:37: 27:50 error: mismatched types:
expected `&mut syntex::Registry`,
found `&mut inner::syntex::Registry`
(expected struct `syntex::Registry`,
found struct `inner::syntex::Registry`) [E0308]
build.rs:27             serde_codegen::register(&mut registry);
                                            ^~~~~~~~~~~~~

Solution is to use codegen without explicit dependency on syntex, see:
https://users.rust-lang.org/t/here-is-how-to-avoid-being-broken-by-syntex-updates/6189?u=dtolnay